/**
 * Pipeline Stage 5: Code Generation
 * ───────────────────────────────────
 * Generates three TypeScript files from topic JSON + Whisper timestamps:
 *   1. PacingEngine.ts — Scene durations, starts, total frames
 *   2. AudioSyncMap.ts — Per-scene cue points
 *   3. topicData.ts    — Scene data, assets, BGM, meta
 *
 * These files are written to src/WealthArchiveVideo/ and replace
 * the previous topic's data. Remotion compiles them at render time.
 */

import { writeFileSync } from "fs";
import type { TopicJSON } from "../schema";
import type { SceneTiming } from "./transcribe";

const FPS = 30;
const OUTPUT_DIR = "src/WealthArchiveVideo";

// ── Color name → constant mapping ────────────────────────────────────────────

const COLOR_MAP: Record<string, string> = {
    GOLD: "C.GOLD",
    OXBLOOD: "C.OXBLOOD",
    CREAM: "C.CREAM",
    CREAM_DIM: "C.CREAM_DIM",
    CREAM_FAINT: "C.CREAM_FAINT",
    GOLD_DIM: "C.GOLD_DIM",
    NAVY: "C.NAVY",
};

function colorRef(name?: string): string {
    if (!name) return "C.CREAM";
    return COLOR_MAP[name] || `"${name}"`;
}

// ══════════════════════════════════════════════════════════════════════════════
// 1. PacingEngine.ts
// ══════════════════════════════════════════════════════════════════════════════

export function generatePacingEngine(
    sceneTimings: SceneTiming[],
    topic: TopicJSON,
): string {
    const durations = sceneTimings.map((st) => st.durationFrames);
    const total = durations.reduce((a, b) => a + b, 0);
    const totalSeconds = (total / FPS).toFixed(1);

    const durationLines = durations
        .map((d, i) => {
            const secs = (d / FPS).toFixed(1);
            const tier =
                d <= 75 ? "STACCATO" :
                d <= 105 ? "MEDIUM" :
                d <= 135 ? "LEGATO" : "EXTENDED";
            const holdEvolve = d > 90 ? " — Hold & Evolve at 90f" : "";
            return `    ${d},${" ".repeat(5 - String(d).length)}// S${i + 1}  — ${tier.padEnd(9)} (${secs}s)${holdEvolve}`;
        })
        .join("\n");

    return `/**
 * WARP 19.0 — Asymmetric Pacing & Audio Sync Engine
 * ────────────────────────────────────────────────────
 * GENERATED by pipeline/stages/generate.ts — DO NOT EDIT MANUALLY
 * Topic: "${topic.meta.title}" (${topic.meta.slug})
 * Total: ${total}f (${totalSeconds}s — matches avatar audio)
 */

export const PACING = {
    MIN_FRAMES: 45,
    MAX_FRAMES: 135,
    HOLD_EVOLVE_AT: 90,
    KINETIC_PREFIX_MIN: 15,
    FPS: ${FPS},
} as const;

export type RhythmTier = "STACCATO" | "MEDIUM" | "LEGATO" | "EXTENDED";

export function getRhythmTier(frames: number): RhythmTier {
    if (frames <= 75)  return "STACCATO";
    if (frames <= 105) return "MEDIUM";
    if (frames <= 135) return "LEGATO";
    return "EXTENDED";
}

export function findRhythmViolation(durations: number[]): number {
    for (let i = 0; i < durations.length - 2; i++) {
        const a = getRhythmTier(durations[i]);
        const b = getRhythmTier(durations[i + 1]);
        const c = getRhythmTier(durations[i + 2]);
        if (a === b && b === c) return i;
    }
    return -1;
}

export function clampDuration(frames: number): number {
    return Math.max(PACING.MIN_FRAMES, frames);
}

export function needsHoldEvolve(frames: number): boolean {
    return frames > PACING.HOLD_EVOLVE_AT;
}

export const WARP19_DURATIONS: readonly number[] = [
${durationLines}
] as const;

export function buildStartFrames(durations: readonly number[]): number[] {
    const starts: number[] = [];
    let cursor = 0;
    for (const d of durations) {
        starts.push(cursor);
        cursor += d;
    }
    return starts;
}

export const WARP19_STARTS = buildStartFrames(WARP19_DURATIONS);
export const WARP19_TOTAL  = WARP19_STARTS[WARP19_STARTS.length - 1] + WARP19_DURATIONS[WARP19_DURATIONS.length - 1];
// = ${total} frames total (${totalSeconds}s)

export function getHoldEvolveTriggers(durationFrames: number): number[] {
    if (durationFrames <= PACING.HOLD_EVOLVE_AT) return [];
    const triggers: number[] = [];
    let t = PACING.HOLD_EVOLVE_AT;
    while (t < durationFrames - 30) {
        triggers.push(t);
        t += PACING.HOLD_EVOLVE_AT;
    }
    return triggers;
}
`;
}

// ══════════════════════════════════════════════════════════════════════════════
// 2. AudioSyncMap.ts
// ══════════════════════════════════════════════════════════════════════════════

export function generateAudioSyncMap(
    sceneTimings: SceneTiming[],
    topic: TopicJSON,
): string {
    const sceneBlocks = sceneTimings.map((st, i) => {
        const scene = topic.scenes[i];
        const narrationPreview = scene.narration.substring(0, 80).replace(/"/g, '\\"');
        const cueLines = st.cuePoints.map((cue) => {
            const wordStr = cue.word.replace(/"/g, '\\"');
            return `        { word: "${wordStr}", frameOffset: ${cue.frameOffset}, event: "${cue.event}" },`;
        });

        return `    // ─── S${i + 1}: "${narrationPreview}"
    // Scene start: ${st.startSeconds.toFixed(2)}s, duration: ${st.durationFrames}f
    [
${cueLines.join("\n")}
    ],`;
    });

    return `/**
 * WARP 19.0 — Audio Sync Map
 * ───────────────────────────
 * GENERATED by pipeline/stages/generate.ts — DO NOT EDIT MANUALLY
 * Topic: "${topic.meta.title}" (${topic.meta.slug})
 * Transcribed from avatar audio via OpenAI Whisper (word_timestamps=True)
 */

export type CueEvent =
    | "SCENE_START"
    | "HERO_WORD"
    | "HARD_CUT"
    | "SOFT_PAUSE"
    | "CHART_DRAW_START"
    | "DATA_STAMP"
    | "EMPHASIS";

export interface SyncCue {
    word: string;
    frameOffset: number;
    event: CueEvent;
}

export const SCENE_CUE_POINTS: SyncCue[][] = [
${sceneBlocks.join("\n\n")}
];

export function getCueFrame(sceneIdx: number, event: CueEvent): number {
    const cues = SCENE_CUE_POINTS[sceneIdx] ?? [];
    return cues.find(c => c.event === event)?.frameOffset ?? 0;
}

export function getAllCueFrames(sceneIdx: number, event: CueEvent): number[] {
    const cues = SCENE_CUE_POINTS[sceneIdx] ?? [];
    return cues.filter(c => c.event === event).map(c => c.frameOffset);
}

export function isCuePassed(localFrame: number, sceneIdx: number, event: CueEvent): boolean {
    return localFrame >= getCueFrame(sceneIdx, event);
}
`;
}

// ══════════════════════════════════════════════════════════════════════════════
// 3. topicData.ts
// ══════════════════════════════════════════════════════════════════════════════

export function generateTopicData(
    topic: TopicJSON,
    assetManifest: Record<string, string>,
): string {
    const slug = topic.meta.slug;

    // Build scene data array
    const sceneEntries = topic.scenes.map((scene) => {
        const i = scene.index;
        const videoAsset = assetManifest[`scene${i}_video`] || "";
        const imageAsset = assetManifest[`scene${i}_image`] || "";

        // Build the scene object as a string
        const parts: string[] = [];
        parts.push(`        index: ${i}`);
        parts.push(`        heroType: "${scene.heroType}"`);
        parts.push(`        environment: "${scene.environment || "VOID"}"`);
        parts.push(`        layout: "${scene.layout || "FULL_BLEED"}"`);
        parts.push(`        physics: "${scene.physics || "SLAM"}"`);
        parts.push(`        narration: ${JSON.stringify(scene.narration)}`);
        parts.push(`        heroWord: "${scene.heroWord}"`);
        if (scene.connectiveWord) parts.push(`        connectiveWord: "${scene.connectiveWord}"`);
        parts.push(`        videoSrc: "${videoAsset}"`);
        parts.push(`        imageSrc: "${imageAsset}"`);

        // Typography
        if (scene.typography) {
            const lines = scene.typography.lines.map((line) => {
                const lineProps: string[] = [];
                lineProps.push(`text: "${line.text}"`);
                lineProps.push(`type: "${line.type}"`);
                lineProps.push(`animation: "${line.animation}"`);
                if (line.weight) lineProps.push(`weight: "${line.weight}"`);
                if (line.color) lineProps.push(`color: ${colorRef(line.color)}`);
                return `            { ${lineProps.join(", ")} }`;
            });
            parts.push(`        typography: {
            lines: [
${lines.join(",\n")}
            ],
            align: "${scene.typography.align || "flex-start"}",
            stagger: ${scene.typography.stagger || 8},
        }`);
        }

        // Declaration
        if (scene.declaration) {
            const lines = scene.declaration.lines.map((line) => {
                return `            { text: "${line.text}", size: ${line.size || 100}, color: ${colorRef(line.color)} }`;
            });
            parts.push(`        declaration: {
            lines: [
${lines.join(",\n")}
            ],
            lineStagger: ${scene.declaration.lineStagger || 10},
        }`);
        }

        // Chart
        if (scene.chart) {
            const dataPoints = scene.chart.data.map((dp) => {
                const sublabel = dp.sublabel ? `, sublabel: "${dp.sublabel}"` : "";
                return `            { label: "${dp.label}", value: ${dp.value}${sublabel} }`;
            });
            let chartStr = `        chart: {
            type: "${scene.chart.type}",
            title: "${scene.chart.title}",
            yUnit: "${scene.chart.yUnit || ""}",
            color: ${colorRef(scene.chart.color)},
            highlightLast: ${scene.chart.highlightLast || false},
            data: [
${dataPoints.join(",\n")}
            ],`;
            if (scene.chart.lineLabel) {
                chartStr += `\n            lineLabel: "${scene.chart.lineLabel}",`;
            }
            if (scene.chart.secondLine) {
                const slData = scene.chart.secondLine.data.map((dp) => {
                    return `                { label: "${dp.label}", value: ${dp.value} }`;
                });
                chartStr += `\n            secondLine: {
                label: "${scene.chart.secondLine.label}",
                color: ${colorRef(scene.chart.secondLine.color)},
                data: [
${slData.join(",\n")}
                ],
            },`;
            }
            chartStr += `\n        }`;
            parts.push(chartStr);
        }

        // DataTicker
        if (scene.dataTicker) {
            parts.push(`        dataTicker: {
            from: ${scene.dataTicker.from ?? 0},
            to: ${scene.dataTicker.to},
            prefix: "${scene.dataTicker.prefix || ""}",
            suffix: "${scene.dataTicker.suffix || ""}",
            decimals: ${scene.dataTicker.decimals ?? 1},
            label: "${scene.dataTicker.label}",
            color: ${colorRef(scene.dataTicker.color)},
        }`);
        }

        // Evidence
        if (scene.evidence) {
            const evParts: string[] = [];
            evParts.push(`type: "${scene.evidence.type}"`);
            if (scene.evidence.leftLabel) evParts.push(`leftLabel: "${scene.evidence.leftLabel}"`);
            if (scene.evidence.leftItems) evParts.push(`leftItems: ${JSON.stringify(scene.evidence.leftItems)}`);
            if (scene.evidence.rightLabel) evParts.push(`rightLabel: "${scene.evidence.rightLabel}"`);
            if (scene.evidence.rightItems) evParts.push(`rightItems: ${JSON.stringify(scene.evidence.rightItems)}`);
            if (scene.evidence.stats) {
                const statsStr = scene.evidence.stats.map((s) =>
                    `{ label: "${s.label}", value: "${s.value}", color: ${colorRef(s.color)} }`
                ).join(", ");
                evParts.push(`stats: [${statsStr}]`);
            }
            if (scene.evidence.fromLabel) evParts.push(`fromLabel: "${scene.evidence.fromLabel}"`);
            if (scene.evidence.toLabel) evParts.push(`toLabel: "${scene.evidence.toLabel}"`);
            if (scene.evidence.throughLabel) evParts.push(`throughLabel: "${scene.evidence.throughLabel}"`);
            parts.push(`        evidence: { ${evParts.join(", ")} }`);
        }

        // MicroReset
        if (scene.microReset) {
            const mrParts = [`type: "${scene.microReset.type}"`];
            if (scene.microReset.label) mrParts.push(`label: "${scene.microReset.label}"`);
            if (scene.microReset.targetElement) mrParts.push(`targetElement: "${scene.microReset.targetElement}"`);
            parts.push(`        microReset: { ${mrParts.join(", ")} }`);

            // SOP Rule: HIGHLIGHTER type MUST have a valid targetElement
            const KNOWN_TARGETS = ["chart-2020", "chart-USA", "right-panel", "CAPEX"];
            if (scene.microReset.type === "HIGHLIGHTER") {
                if (!scene.microReset.targetElement) {
                    console.warn(`  ⚠️  SOP VIOLATION: Scene ${scene.index} uses HIGHLIGHTER without targetElement — circle will NOT render.`);
                } else if (!KNOWN_TARGETS.includes(scene.microReset.targetElement)) {
                    console.warn(`  ⚠️  SOP WARNING: Scene ${scene.index} HIGHLIGHTER targets unknown element "${scene.microReset.targetElement}" — add to resolveHighlighterTarget() in MicroAnimationReset.tsx.`);
                }
            }
        }

        // Source
        if (scene.source) {
            parts.push(`        source: { classification: "${scene.source.classification}", citation: "${scene.source.citation}" }`);
        }

        return `    {\n${parts.join(",\n")},\n    }`;
    });

    // Build transitions array
    const transLines = topic.transitions.map((t) =>
        `    { from: ${t.from}, to: ${t.to}, type: "${t.type}" }`
    );

    return `/**
 * Topic Data — Runtime Scene Configuration
 * ─────────────────────────────────────────
 * GENERATED by pipeline/stages/generate.ts — DO NOT EDIT MANUALLY
 * Topic: "${topic.meta.title}" (${topic.meta.slug})
 */

import { C } from "./fonts";

export const TOPIC_META = {
    title: "${topic.meta.title}",
    slug: "${slug}",
    archetype: "${topic.meta.archetype || "HIDDEN_MECHANISM"}",
} as const;

export const AVATAR_FILE = "topics/${slug}/avatar.mp4";
export const NARRATION_FILE = "topics/${slug}/narration.mp3";
export const BGM_FILE = "bgm/${topic.bgm.trackId}.mp3";

export const TOPIC_TRANSITIONS = [
${transLines.join(",\n")}
] as const;

export const TOPIC_SCENES = [
${sceneEntries.join(",\n")}
] as const;
`;
}

// ══════════════════════════════════════════════════════════════════════════════
// Main: Write all generated files
// ══════════════════════════════════════════════════════════════════════════════

// ══════════════════════════════════════════════════════════════════════════════
// 4. SfxMap.ts — Sound Effect trigger events mapped to absolute frames
// ══════════════════════════════════════════════════════════════════════════════

interface SfxManifestEntry {
    file: string;
    volume: number;
    freesoundId: number;
    name: string;
    duration: number;
    license: string;
    onsetSec?: number;    // seconds of leading silence to skip
}

function generateSfxMap(
    topic: TopicJSON,
    sceneTimings: SceneTiming[],
    sfxManifest: Record<string, SfxManifestEntry>,
): string {
    if (Object.keys(sfxManifest).length === 0) {
        return `/**\n * SfxMap — No SFX available\n */\nexport interface SfxEvent { absoluteFrame: number; sfxFile: string; volume: number; startFrom: number; label: string; }\nexport const SFX_EVENTS: SfxEvent[] = [];\n`;
    }

    // Build cumulative scene starts
    const starts: number[] = [];
    let cum = 0;
    for (const t of sceneTimings) {
        starts.push(cum);
        cum += t.durationFrames;
    }

    const FPS_SFX = 30;
    const events: Array<{ absoluteFrame: number; sfxFile: string; volume: number; startFrom: number; label: string }> = [];
    const HOLD_EVOLVE_AT = 90; // from PacingEngine PACING constant

    // Helper: convert onset seconds → frames, rounding down for safety
    const onsetFrames = (key: string): number => {
        const sec = sfxManifest[key]?.onsetSec ?? 0;
        return Math.floor(sec * FPS_SFX);
    };

    for (let i = 0; i < topic.scenes.length; i++) {
        const scene = topic.scenes[i];
        const sceneStart = starts[i];
        const sceneDur = sceneTimings[i].durationFrames;
        const cues = sceneTimings[i].cuePoints;

        // Helper: get cue frame offset for this scene
        const getCue = (event: string): number => {
            const cue = cues.find((c) => c.event === event);
            return cue ? cue.frameOffset : 0;
        };

        // ── STOMP_IMPACT: fires at HERO_WORD for scenes with STOMP typography
        if (sfxManifest["STOMP_IMPACT"] && scene.typography?.lines.some((l: any) => l.animation === "STOMP")) {
            events.push({
                absoluteFrame: sceneStart + getCue("HERO_WORD"),
                sfxFile: sfxManifest["STOMP_IMPACT"].file,
                volume: sfxManifest["STOMP_IMPACT"].volume,
                startFrom: onsetFrames("STOMP_IMPACT"),
                label: `S${scene.index} STOMP @ HERO_WORD`,
            });
        }

        // ── CHART_DRAW: fires at CHART_DRAW_START for chart scenes
        if (sfxManifest["CHART_DRAW"] && scene.chart) {
            events.push({
                absoluteFrame: sceneStart + getCue("CHART_DRAW_START"),
                sfxFile: sfxManifest["CHART_DRAW"].file,
                volume: sfxManifest["CHART_DRAW"].volume,
                startFrom: onsetFrames("CHART_DRAW"),
                label: `S${scene.index} CHART_DRAW`,
            });
        }

        // ── HIGHLIGHTER_CIRCLE: fires at Hold & Evolve trigger (f90) for HIGHLIGHTER scenes
        if (sfxManifest["HIGHLIGHTER_CIRCLE"] && scene.microReset?.type === "HIGHLIGHTER" && sceneDur > HOLD_EVOLVE_AT) {
            events.push({
                absoluteFrame: sceneStart + HOLD_EVOLVE_AT,
                sfxFile: sfxManifest["HIGHLIGHTER_CIRCLE"].file,
                volume: sfxManifest["HIGHLIGHTER_CIRCLE"].volume,
                startFrom: onsetFrames("HIGHLIGHTER_CIRCLE"),
                label: `S${scene.index} HIGHLIGHTER @ f${HOLD_EVOLVE_AT}`,
            });
        }

        // ── REDACTION_REVEAL: fires at Hold & Evolve trigger for REDACTION scenes
        if (sfxManifest["REDACTION_REVEAL"] && scene.microReset?.type === "REDACTION_REVEAL" && sceneDur > HOLD_EVOLVE_AT) {
            events.push({
                absoluteFrame: sceneStart + HOLD_EVOLVE_AT,
                sfxFile: sfxManifest["REDACTION_REVEAL"].file,
                volume: sfxManifest["REDACTION_REVEAL"].volume,
                startFrom: onsetFrames("REDACTION_REVEAL"),
                label: `S${scene.index} REDACTION_REVEAL @ f${HOLD_EVOLVE_AT}`,
            });
        }
    }

    // ── Transition SFX: fire at scene boundary (= start of destination scene)
    // The camera whip-pan / visual transition starts exactly at the boundary
    // between source and destination scenes, so SFX must hit at that instant.
    for (const t of topic.transitions) {
        const toIdx = t.to - 1; // 0-indexed destination scene
        const transFrame = starts[toIdx]; // exact scene boundary

        if (t.type === "Z_AXIS_PORTAL" && sfxManifest["Z_AXIS_SWOOSH"]) {
            events.push({
                absoluteFrame: transFrame,
                sfxFile: sfxManifest["Z_AXIS_SWOOSH"].file,
                volume: sfxManifest["Z_AXIS_SWOOSH"].volume,
                startFrom: onsetFrames("Z_AXIS_SWOOSH"),
                label: `S${t.from}→S${t.to} Z_AXIS_PORTAL`,
            });
        }
        if (t.type === "FLASHBULB" && sfxManifest["FLASHBULB_SHUTTER"]) {
            events.push({
                absoluteFrame: transFrame,
                sfxFile: sfxManifest["FLASHBULB_SHUTTER"].file,
                volume: sfxManifest["FLASHBULB_SHUTTER"].volume,
                startFrom: onsetFrames("FLASHBULB_SHUTTER"),
                label: `S${t.from}→S${t.to} FLASHBULB`,
            });
        }
        if (t.type === "INK_BLEED" && sfxManifest["INK_BLEED"]) {
            events.push({
                absoluteFrame: transFrame,
                sfxFile: sfxManifest["INK_BLEED"].file,
                volume: sfxManifest["INK_BLEED"].volume,
                startFrom: onsetFrames("INK_BLEED"),
                label: `S${t.from}→S${t.to} INK_BLEED`,
            });
        }
    }

    // Sort by absolute frame
    events.sort((a, b) => a.absoluteFrame - b.absoluteFrame);

    // Generate TypeScript
    const lines = [
        `/**`,
        ` * SfxMap — Sound Effect Events`,
        ` * ─────────────────────────────`,
        ` * GENERATED by pipeline/stages/generate.ts — DO NOT EDIT MANUALLY`,
        ` * Topic: "${topic.meta.title}" (${topic.meta.slug})`,
        ` * ${events.length} SFX events mapped to absolute frames`,
        ` */`,
        ``,
        `export interface SfxEvent {`,
        `    absoluteFrame: number;`,
        `    sfxFile: string;`,
        `    volume: number;`,
        `    startFrom: number;`,
        `    label: string;`,
        `}`,
        ``,
        `export const SFX_EVENTS: SfxEvent[] = [`,
    ];

    for (const evt of events) {
        lines.push(`    { absoluteFrame: ${evt.absoluteFrame}, sfxFile: "${evt.sfxFile}", volume: ${evt.volume}, startFrom: ${evt.startFrom}, label: "${evt.label}" },`);
    }

    lines.push(`];`);
    lines.push(``);

    return lines.join("\n");
}

export function generateAllFiles(
    topic: TopicJSON,
    sceneTimings: SceneTiming[],
    assetManifest: Record<string, string>,
    sfxManifest?: Record<string, SfxManifestEntry>,
): { pacingPath: string; syncPath: string; dataPath: string; sfxPath?: string } {
    console.log("  🔧 Generating PacingEngine.ts...");
    const pacingContent = generatePacingEngine(sceneTimings, topic);
    const pacingPath = `${OUTPUT_DIR}/PacingEngine.ts`;
    writeFileSync(pacingPath, pacingContent);

    console.log("  🔧 Generating AudioSyncMap.ts...");
    const syncContent = generateAudioSyncMap(sceneTimings, topic);
    const syncPath = `${OUTPUT_DIR}/AudioSyncMap.ts`;
    writeFileSync(syncContent.length > 0 ? syncPath : syncPath, syncContent);

    console.log("  🔧 Generating topicData.ts...");
    const dataContent = generateTopicData(topic, assetManifest);
    const dataPath = `${OUTPUT_DIR}/topicData.ts`;
    writeFileSync(dataPath, dataContent);

    let sfxPath: string | undefined;
    if (sfxManifest && Object.keys(sfxManifest).length > 0) {
        console.log("  🔧 Generating SfxMap.ts...");
        const sfxContent = generateSfxMap(topic, sceneTimings, sfxManifest);
        sfxPath = `${OUTPUT_DIR}/SfxMap.ts`;
        writeFileSync(sfxPath, sfxContent);
        console.log(`  ✅ Generated 4 files to ${OUTPUT_DIR}/`);
    } else {
        console.log(`  ✅ Generated 3 files to ${OUTPUT_DIR}/`);
    }

    return { pacingPath, syncPath, dataPath, sfxPath };
}
