/**
 * WARP 19.0 — Audio Sync Map
 * ───────────────────────────
 * GENERATED by pipeline/stages/generate.ts — DO NOT EDIT MANUALLY
 * Topic: "Resulting" (resulting)
 * Transcribed from avatar audio via OpenAI Whisper (word_timestamps=True)
 */

export type CueEvent =
    | "SCENE_START"
    | "HERO_WORD"
    | "HARD_CUT"
    | "SOFT_PAUSE"
    | "CHART_DRAW_START"
    | "DATA_STAMP"
    | "EMPHASIS";

export interface SyncCue {
    word: string;
    frameOffset: number;
    event: CueEvent;
}

export const SCENE_CUE_POINTS: SyncCue[][] = [
    // ─── S1: "Your best decisions can produce your worst outcomes."
    // Scene start: 0.00s, duration: 114f
    [
        { word: " Your", frameOffset: 0, event: "SCENE_START" },
        { word: " best", frameOffset: 7, event: "EMPHASIS" },
        { word: " outcomes.", frameOffset: 88, event: "HERO_WORD" },
        { word: " outcomes.", frameOffset: 88, event: "HARD_CUT" },
    ],

    // ─── S2: "That mistake has a name: Resulting."
    // Scene start: 3.80s, duration: 101f
    [
        { word: " That", frameOffset: 12, event: "SCENE_START" },
        { word: " name,", frameOffset: 47, event: "SOFT_PAUSE" },
        { word: " resulting,", frameOffset: 75, event: "HERO_WORD" },
        { word: " resulting,", frameOffset: 75, event: "SOFT_PAUSE" },
    ],

    // ─── S3: "It quietly destroys fortunes."
    // Scene start: 7.17s, duration: 95f
    [
        { word: " and", frameOffset: 3, event: "SCENE_START" },
        { word: " destroys", frameOffset: 26, event: "HERO_WORD" },
        { word: " fortunes.", frameOffset: 48, event: "HARD_CUT" },
    ],

    // ─── S4: "In 2015, one pass play lost the Seattle Seahawks the Super Bowl."
    // Scene start: 10.34s, duration: 163f
    [
        { word: " In", frameOffset: 0, event: "SCENE_START" },
        { word: " 2015,", frameOffset: 13, event: "SOFT_PAUSE" },
        { word: " lost", frameOffset: 82, event: "HERO_WORD" },
        { word: " Seahawks,", frameOffset: 114, event: "SOFT_PAUSE" },
        { word: " Bowl.", frameOffset: 147, event: "HARD_CUT" },
    ],

    // ─── S5: "Commentators called it the worst call in history. They were wrong."
    // Scene start: 15.78s, duration: 152f
    [
        { word: " Commentators", frameOffset: 11, event: "SCENE_START" },
        { word: " history.", frameOffset: 81, event: "HARD_CUT" },
        { word: " wrong.", frameOffset: 132, event: "HERO_WORD" },
        { word: " wrong.", frameOffset: 132, event: "HARD_CUT" },
    ],

    // ─── S6: "They judged the decision by the outcome instead of the odds."
    // Scene start: 20.84s, duration: 124f
    [
        { word: " They", frameOffset: 11, event: "SCENE_START" },
        { word: " They", frameOffset: 15, event: "CHART_DRAW_START" },
        { word: " odds.", frameOffset: 105, event: "HERO_WORD" },
        { word: " odds.", frameOffset: 105, event: "HARD_CUT" },
    ],

    // ─── S7: "The hidden force is variance. Luck is just noise in the data."
    // Scene start: 24.98s, duration: 178f
    [
        { word: " The", frameOffset: 10, event: "SCENE_START" },
        { word: " The", frameOffset: 15, event: "CHART_DRAW_START" },
        { word: " variance.", frameOffset: 45, event: "HERO_WORD" },
        { word: " variance.", frameOffset: 45, event: "HARD_CUT" },
        { word: " data.", frameOffset: 153, event: "HARD_CUT" },
    ],

    // ─── S8: "If you drive home drunk and survive, was it a good decision?"
    // Scene start: 30.90s, duration: 124f
    [
        { word: " If", frameOffset: 17, event: "SCENE_START" },
        { word: " survive,", frameOffset: 55, event: "SOFT_PAUSE" },
        { word: " good", frameOffset: 94, event: "HERO_WORD" },
        { word: " decision?", frameOffset: 98, event: "HARD_CUT" },
    ],

    // ─── S9: "Markets reward the lucky amateur and punish the disciplined professional."
    // Scene start: 35.02s, duration: 150f
    [
        { word: " Markets", frameOffset: 13, event: "SCENE_START" },
        { word: " Markets", frameOffset: 15, event: "CHART_DRAW_START" },
        { word: " reward", frameOffset: 28, event: "HERO_WORD" },
        { word: " professional.", frameOffset: 121, event: "HARD_CUT" },
    ],

    // ─── S10: "Over time, that incentive structure erodes real capital."
    // Scene start: 40.03s, duration: 138f
    [
        { word: " Over", frameOffset: 9, event: "SCENE_START" },
        { word: " time,", frameOffset: 19, event: "SOFT_PAUSE" },
        { word: " erodes", frameOffset: 79, event: "HERO_WORD" },
        { word: " capital.", frameOffset: 110, event: "HARD_CUT" },
    ],

    // ─── S11: "Winners separate process from outcome."
    // Scene start: 44.62s, duration: 91f
    [
        { word: " Winners", frameOffset: 11, event: "SCENE_START" },
        { word: " separate", frameOffset: 20, event: "HERO_WORD" },
        { word: " outcome.", frameOffset: 67, event: "HARD_CUT" },
    ],

    // ─── S12: "You evaluate the bet before the card is revealed. Stop judging results. Start th"
    // Scene start: 47.68s, duration: 207f
    [
        { word: " You", frameOffset: 10, event: "SCENE_START" },
        { word: " bet", frameOffset: 37, event: "HERO_WORD" },
        { word: " revealed.", frameOffset: 80, event: "HARD_CUT" },
        { word: " results.", frameOffset: 135, event: "HARD_CUT" },
        { word: " bets.", frameOffset: 197, event: "HARD_CUT" },
    ],
];

export function getCueFrame(sceneIdx: number, event: CueEvent): number {
    const cues = SCENE_CUE_POINTS[sceneIdx] ?? [];
    return cues.find(c => c.event === event)?.frameOffset ?? 0;
}

export function getAllCueFrames(sceneIdx: number, event: CueEvent): number[] {
    const cues = SCENE_CUE_POINTS[sceneIdx] ?? [];
    return cues.filter(c => c.event === event).map(c => c.frameOffset);
}

export function isCuePassed(localFrame: number, sceneIdx: number, event: CueEvent): boolean {
    return localFrame >= getCueFrame(sceneIdx, event);
}
