
import React from "react";
import { AbsoluteFill, Audio, Sequence, useCurrentFrame, useVideoConfig, spring, staticFile, interpolate } from "remotion";
import { GlobalLens } from "./GlobalLens";
import { C } from "./fonts";
import { TransitionWrapper, TransitionType } from "./Transitions/TransitionWrapper";
// EnvironmentLayer is handled per-scene inside ArchiveScene.tsx (line 327).
// REMOVED global atmosphere video — it caused render crashes (3 concurrent ffmpeg streams at scene transitions).
import { WARP19_DURATIONS, WARP19_STARTS } from "./PacingEngine";
import { PhantomHost } from "./PhantomHost";
import { SceneRenderer } from "./SceneRenderer";
import { TOPIC_SCENES, TOPIC_TRANSITIONS, AVATAR_FILE, NARRATION_FILE, BGM_FILE } from "./topicData";
import { SFX_EVENTS } from "./SfxMap";
import assetsRaw from "./assets.json";
// Try to import processed assets if they exist, otherwise fallback
import processedAssets from "./assets.processed.json";
const assets = { ...assetsRaw, ...processedAssets };

/*
 * THE WEALTH ARCHIVE — Main Composition (Data-Driven)
 * ─────────────────────────────────────────────────────
 * All scene content, transitions, and visual parameters are now driven
 * by topicData.ts (generated by the pipeline from topic.json).
 *
 * Camera rove engine, transition matrix, and virtual desk grid remain.
 * Scene rendering is delegated to SceneRenderer.tsx.
 *
 * ┌─────────────────────────────────────────────────────────────┐
 * │  CAMERA ROVE ENGINE                                         │
 * │  All scenes live at absolute positions on a virtual         │
 * │  4320 × 5760px desk (4 cols × 3 rows). The viewport        │
 * │  (1080 × 1920) translates between scenes using a harsh      │
 * │  spring (stiffness: 280, damping: 18) — whip-pan with       │
 * │  physical overshoot. No fades. No dissolves.                │
 * │                                                             │
 * │  Grid:                                                      │
 * │  S1(0,0)  S2(1,0)  S3(2,0)  S4(3,0)                        │
 * │  S5(0,1)  S6(1,1)  S7(2,1)  S8(3,1)                        │
 * │  S9(0,2) S10(1,2) S11(2,2) S12(3,2)                        │
 * └─────────────────────────────────────────────────────────────┘
 */

// ─── Grid positions — derived from scene count ──────────────────────────────
const GRID_COLUMNS = 4;
const GRID_POSITIONS = TOPIC_SCENES.map((_, i) => ({
    col: i % GRID_COLUMNS,
    row: Math.floor(i / GRID_COLUMNS),
}));

const SCENES = GRID_POSITIONS.map((pos, i) => ({
    start: WARP19_STARTS[i],
    dur:   WARP19_DURATIONS[i],
    col:   pos.col,
    row:   pos.row,
}));

// ─── Build transition type array from topic data ────────────────────────────
// TOPIC_TRANSITIONS maps {from, to, type}. We need a flat array indexed by scene.
// Index i = transition from scene i to scene i+1. Last element is "NONE".
const TRANSITIONS: TransitionType[] = (() => {
    const arr: TransitionType[] = [];
    for (let i = 0; i < TOPIC_SCENES.length; i++) {
        const t = TOPIC_TRANSITIONS.find((tr) => tr.from === i + 1);
        arr.push(t ? (t.type as TransitionType) : "NONE");
    }
    return arr;
})();

// ─── Camera rove hook ────────────────────────────────────────────────────────
function useCameraPosition(): { x: number; y: number } {
    const frame = useCurrentFrame();
    const { fps } = useVideoConfig();

    // Find which scene we're currently in
    let currIdx = 0;
    for (let i = 0; i < SCENES.length; i++) {
        if (frame >= SCENES[i].start) currIdx = i;
    }

    const curr = SCENES[currIdx];
    const prev = currIdx > 0 ? SCENES[currIdx - 1] : curr;

    const targetX = curr.col * 1080;
    const targetY = curr.row * 1920;
    const prevX = prev.col * 1080;
    const prevY = prev.row * 1920;

    // Spring: stiffness 280, damping 18 → pronounced overshoot whip-pan
    const panP = spring({
        frame: frame - curr.start,
        fps,
        config: { stiffness: 280, damping: 18, mass: 1 },
    });

    // Allow overshoot (panP can exceed 1.0 with low damping)
    const x = prevX + (targetX - prevX) * panP;
    const y = prevY + (targetY - prevY) * panP;

    return { x, y };
}

// ─── Main composition ────────────────────────────────────────────────────────
export const WealthArchiveVideo: React.FC = () => {
    const frame = useCurrentFrame();
    const { x: camX, y: camY } = useCameraPosition();

    // Local frame per scene
    const lf = (sceneIdx: number) => frame - SCENES[sceneIdx].start;

    // SCENE CULLING: Only render scenes that are currently visible or in transition
    // Buffer of 15 frames — spring whip-pan settles in ~12 frames (stiffness 280, damping 18).
    // Reduced from 40 to minimize concurrent OffthreadVideo instances during transitions.
    const isVisible = (idx: number) => {
        const { start, dur } = SCENES[idx];
        const end = start + dur;
        return frame >= start - 15 && frame <= end + 15;
    };

    // Helper to get Transition Props for a specific scene
    const getTransProps = (idx: number) => {
        const { start, dur } = SCENES[idx];
        const local = frame - start;
        const isEntering = local < 30;
        const isExiting = local > dur - 30;

        let type: TransitionType = "NONE";
        if (isEntering && idx > 0) type = TRANSITIONS[idx - 1];
        else if (isExiting && idx < TRANSITIONS.length) type = TRANSITIONS[idx];

        return { type, entering: isEntering, exiting: isExiting, duration: dur };
    };

    // Virtual desk dimensions
    const deskCols = Math.max(...GRID_POSITIONS.map((p) => p.col)) + 1;
    const deskRows = Math.max(...GRID_POSITIONS.map((p) => p.row)) + 1;

    return (
        <AbsoluteFill style={{ backgroundColor: C.NAVY, overflow: "hidden" }}>
            {/* ROOT BACKGROUND: Static CSS atmosphere — no video decode.
                The per-scene EnvironmentLayer in ArchiveScene.tsx handles IMMERSIVE_BLEED
                when a scene's variant requires it. Removed global OffthreadVideo that was
                causing 3 concurrent ffmpeg streams and render crashes at frame ~1450. */}
            <AbsoluteFill style={{
                backgroundImage: `
                    radial-gradient(ellipse at 30% 20%, rgba(197, 160, 89, 0.06) 0%, transparent 60%),
                    radial-gradient(ellipse at 70% 80%, rgba(197, 160, 89, 0.04) 0%, transparent 50%)
                `,
            }} />

            {/* Full narration audio — lightweight MP3 extracted from avatar.mp4.
                Using separate MP3 avoids OffthreadVideo seeking avatar.mp4 for every audio frame. */}
            <Audio src={staticFile(NARRATION_FILE)} />

            {/* ── BGM LAYER with AUTO-DUCKING ─────────────────────────────────
                WARP Audio Mixing SOP:
                  - BGM_AMBIENT:  0.45 — heard during silence / intro / outro
                  - BGM_DUCKED:   0.18 — reduced under active narration
                  - INTRO_RAMP:   0→15f — BGM rises before voice begins
                  - VOICE_DUCK:   15f → (totalFrames-45) — ducked under narration
                  - OUTRO_SWELL:  last 45f — BGM swells back as voice ends
                This keeps the bed clearly present without competing with narrator.
            ──────────────────────────────────────────────────────────────── */}
            <Audio
                src={staticFile(BGM_FILE)}
                volume={(f) => {
                    const totalFrames = WARP19_DURATIONS.reduce((a, b) => a + b, 0);
                    const BGM_AMBIENT = 0.45;
                    const BGM_DUCKED  = 0.18;
                    const INTRO_END   = 15;          // voice kicks in ~frame 15
                    const OUTRO_START = totalFrames - 45; // last 45f = swell
                    if (f <= INTRO_END) {
                        // Ramp from 0 → BGM_AMBIENT over first 15 frames
                        return interpolate(f, [0, INTRO_END], [0, BGM_AMBIENT], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
                    }
                    if (f >= OUTRO_START) {
                        // Swell back from BGM_DUCKED → BGM_AMBIENT over last 45 frames
                        return interpolate(f, [OUTRO_START, totalFrames], [BGM_DUCKED, BGM_AMBIENT], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
                    }
                    // Mid-video: ducked under narration
                    return BGM_DUCKED;
                }}
            />

            {/* ── SFX LAYER — Foley synced to visual events ─────────────────────
                WARP Audio Mixing SOP (Part XII §12):
                  - Each SFX fires at an absolute frame tied to its visual event
                  - Volume: 0.30–0.60 per event type (between narration and BGM)
                  - Onset = visual event frame. No pre-roll.
                  - Events: STOMP_IMPACT, HIGHLIGHTER_CIRCLE, Z_AXIS_SWOOSH,
                    FLASHBULB_SHUTTER, REDACTION_REVEAL, INK_BLEED, CHART_DRAW
            ──────────────────────────────────────────────────────────────── */}
            {SFX_EVENTS.map((sfx, i) => (
                <Sequence key={`sfx-${i}`} from={sfx.absoluteFrame} layout="none">
                    <Audio
                        src={staticFile(sfx.sfxFile)}
                        volume={sfx.volume}
                        startFrom={sfx.startFrom}
                    />
                </Sequence>
            ))}

            {/* ═══ VIRTUAL DESK — all scenes positioned on grid ════════════════ */}
            <div
                style={{
                    position: "absolute",
                    width: deskCols * 1080,
                    height: deskRows * 1920,
                    transform: `translate(${-camX}px, ${-camY}px)`,
                    willChange: "transform",
                }}
            >
                {TOPIC_SCENES.map((scene, idx) => {
                    if (!isVisible(idx)) return null;

                    const pos = GRID_POSITIONS[idx];
                    const left = pos.col * 1080;
                    const top = pos.row * 1920;

                    return (
                        <div
                            key={scene.index}
                            style={{
                                position: "absolute",
                                left,
                                top,
                                width: 1080,
                                height: 1920,
                            }}
                        >
                            <TransitionWrapper {...getTransProps(idx)} frame={lf(idx)}>
                                <SceneRenderer
                                    scene={scene}
                                    sceneIdx={idx}
                                    localFrame={lf(idx)}
                                    sceneDuration={SCENES[idx].dur}
                                    assets={assets}
                                />
                            </TransitionWrapper>
                        </div>
                    );
                })}
            </div>

            {/* WARP v2.0 Part VIII: The Phantom Host Protocol */}
            <PhantomHost />

            <GlobalLens />
        </AbsoluteFill>
    );
};
