/**
 * WARP 19.0 — Asymmetric Pacing & Audio Sync Engine
 * ────────────────────────────────────────────────────
 * GENERATED by pipeline/stages/generate.ts — DO NOT EDIT MANUALLY
 * Topic: "Resulting" (resulting)
 * Total: 1637f (54.6s — matches avatar audio)
 */

export const PACING = {
    MIN_FRAMES: 45,
    MAX_FRAMES: 135,
    HOLD_EVOLVE_AT: 90,
    KINETIC_PREFIX_MIN: 15,
    FPS: 30,
} as const;

export type RhythmTier = "STACCATO" | "MEDIUM" | "LEGATO" | "EXTENDED";

export function getRhythmTier(frames: number): RhythmTier {
    if (frames <= 75)  return "STACCATO";
    if (frames <= 105) return "MEDIUM";
    if (frames <= 135) return "LEGATO";
    return "EXTENDED";
}

export function findRhythmViolation(durations: number[]): number {
    for (let i = 0; i < durations.length - 2; i++) {
        const a = getRhythmTier(durations[i]);
        const b = getRhythmTier(durations[i + 1]);
        const c = getRhythmTier(durations[i + 2]);
        if (a === b && b === c) return i;
    }
    return -1;
}

export function clampDuration(frames: number): number {
    return Math.max(PACING.MIN_FRAMES, frames);
}

export function needsHoldEvolve(frames: number): boolean {
    return frames > PACING.HOLD_EVOLVE_AT;
}

export const WARP19_DURATIONS: readonly number[] = [
    114,  // S1  — LEGATO    (3.8s) — Hold & Evolve at 90f
    101,  // S2  — MEDIUM    (3.4s) — Hold & Evolve at 90f
    95,   // S3  — MEDIUM    (3.2s) — Hold & Evolve at 90f
    163,  // S4  — EXTENDED  (5.4s) — Hold & Evolve at 90f
    152,  // S5  — EXTENDED  (5.1s) — Hold & Evolve at 90f
    124,  // S6  — LEGATO    (4.1s) — Hold & Evolve at 90f
    178,  // S7  — EXTENDED  (5.9s) — Hold & Evolve at 90f
    124,  // S8  — LEGATO    (4.1s) — Hold & Evolve at 90f
    150,  // S9  — EXTENDED  (5.0s) — Hold & Evolve at 90f
    138,  // S10  — EXTENDED  (4.6s) — Hold & Evolve at 90f
    91,   // S11  — MEDIUM    (3.0s) — Hold & Evolve at 90f
    207,  // S12  — EXTENDED  (6.9s) — Hold & Evolve at 90f
] as const;

export function buildStartFrames(durations: readonly number[]): number[] {
    const starts: number[] = [];
    let cursor = 0;
    for (const d of durations) {
        starts.push(cursor);
        cursor += d;
    }
    return starts;
}

export const WARP19_STARTS = buildStartFrames(WARP19_DURATIONS);
export const WARP19_TOTAL  = WARP19_STARTS[WARP19_STARTS.length - 1] + WARP19_DURATIONS[WARP19_DURATIONS.length - 1];
// = 1637 frames total (54.6s)

export function getHoldEvolveTriggers(durationFrames: number): number[] {
    if (durationFrames <= PACING.HOLD_EVOLVE_AT) return [];
    const triggers: number[] = [];
    let t = PACING.HOLD_EVOLVE_AT;
    while (t < durationFrames - 30) {
        triggers.push(t);
        t += PACING.HOLD_EVOLVE_AT;
    }
    return triggers;
}
