import React from "react";
import {
    AbsoluteFill,
    useCurrentFrame,
    staticFile,
    OffthreadVideo,
    interpolate,
} from "remotion";
import { C } from "./fonts";
import { WARP19_TOTAL, WARP19_STARTS } from "./PacingEngine";
import { AVATAR_FILE } from "./topicData";

/**
 * WARP v2.0 SOP Part VIII: THE PHANTOM HOST PROTOCOL
 * ───────────────────────────────────────────────────
 * MANDATORY. Every composition includes a full avatar narration video.
 *
 * The avatar is visible for only ~15% of total composition duration,
 * appearing in exactly THREE windows:
 *
 *   1. HOOK     — Frames 0–45 (1.5s). Face on screen immediately.
 *   2. BRIDGE   — One mid-video appearance (60 frames / 2.0s).
 *   3. VERDICT  — Final 90 frames (3.0s). Concluding statement.
 *
 * Visual Treatment (Interrogation Grade):
 *   filter: grayscale(0.4) contrast(1.4) brightness(0.6) sepia(0.2)
 *   + tight radial vignette mask
 *
 * Jump Cut: 100% → 115% scale mid-sentence in each window.
 *
 * Z-Index: 8 (Layer 5.5 — between Signal z≤6 and GlobalLens z=9999).
 * The virtual desk div uses CSS transform which creates a stacking context,
 * so z=8 paints above the entire desk, below GlobalLens.
 *
 * The avatar is intentionally BENEATH the GlobalLens — film grain and
 * vignette MUST overlay the avatar's face to maintain archival aesthetic.
 */

// ─── AVATAR SOURCE ──────────────────────────────────────────────────────────
// Dynamic: reads from topicData.ts (generated by pipeline or hand-written)
const AVATAR_SRC = staticFile(AVATAR_FILE);

// ─── WINDOW DEFINITIONS ────────────────────────────────────────────────────
// Hook: First 1.5 seconds — immediate face
const HOOK_START = 0;
const HOOK_END = 45;

// Bridge: Mid-video dramatic pivot at S7 start ("Inflation is a policy choice")
// S7 starts at ~51.7% of total — near the midpoint
const BRIDGE_START = WARP19_STARTS[6]; // S7 start (dynamically computed)
const BRIDGE_END = BRIDGE_START + 60; // 60 frames = 2.0s

// Verdict: Last 90 frames of the composition
const VERDICT_START = WARP19_TOTAL - 90; // 1613 - 90 = 1523
const VERDICT_END = WARP19_TOTAL; // 1613

// ─── JUMP CUT FRAMES ───────────────────────────────────────────────────────
// Mid-sentence punches from 100% to 115% scale within each window
const HOOK_JUMP_FRAME = 22; // ~0.7s — syncs with "printing" word
const BRIDGE_JUMP_FRAME = BRIDGE_START + 30; // 30f into bridge — mid-sentence
const VERDICT_JUMP_FRAME = VERDICT_START + 45; // ~1.5s into verdict — "new operator"

// ─── CAMERA SCALES ──────────────────────────────────────────────────────────
const BASE_SCALE = 1.25; // Medium close-up (chops off hands/desk)
const JUMP_SCALE = 1.44; // 115% of base ≈ 1.25 * 1.15 = 1.4375 → 1.44

// ─── FADE DURATION ──────────────────────────────────────────────────────────
const FADE_FRAMES = 3; // 3-frame hard cut in/out

// ─── TYPES ──────────────────────────────────────────────────────────────────
type PhantomWindow = "HOOK" | "BRIDGE" | "VERDICT";

interface WindowDef {
    start: number;
    end: number;
    jumpFrame: number;
}

const WINDOWS: Record<PhantomWindow, WindowDef> = {
    HOOK: { start: HOOK_START, end: HOOK_END, jumpFrame: HOOK_JUMP_FRAME },
    BRIDGE: {
        start: BRIDGE_START,
        end: BRIDGE_END,
        jumpFrame: BRIDGE_JUMP_FRAME,
    },
    VERDICT: {
        start: VERDICT_START,
        end: VERDICT_END,
        jumpFrame: VERDICT_JUMP_FRAME,
    },
};

function getActiveWindow(frame: number): PhantomWindow | null {
    if (frame >= HOOK_START && frame < HOOK_END) return "HOOK";
    if (frame >= BRIDGE_START && frame < BRIDGE_END) return "BRIDGE";
    if (frame >= VERDICT_START && frame <= VERDICT_END) return "VERDICT";
    return null;
}

// ─── COMPONENT ──────────────────────────────────────────────────────────────
export const PhantomHost: React.FC = () => {
    const frame = useCurrentFrame();

    const windowName = getActiveWindow(frame);
    if (!windowName) return null;

    const win = WINDOWS[windowName];
    const localFrame = frame - win.start;
    const windowDur = win.end - win.start;

    // Jump cut: snap from base to 115% scale after the jump frame
    const cameraScale = frame >= win.jumpFrame ? JUMP_SCALE : BASE_SCALE;

    // 3-frame hard cut in, 3-frame hard cut out
    const opacity = interpolate(
        localFrame,
        [0, FADE_FRAMES, windowDur - FADE_FRAMES, windowDur],
        [0, 1, 1, 0],
        { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
    );

    return (
        <AbsoluteFill
            style={{
                backgroundColor: C.NAVY, // The Substrate Backdrop
                zIndex: 8, // Layer 5.5: above scenes, below GlobalLens (9999)
                justifyContent: "center",
                alignItems: "center",
                overflow: "hidden",
                opacity,
            }}
        >
            {/* Interrogation vignette mask — tight radial, darkened edges */}
            <AbsoluteFill
                style={{
                    WebkitMaskImage:
                        "radial-gradient(circle, black 40%, transparent 90%)",
                    maskImage:
                        "radial-gradient(circle, black 40%, transparent 90%)",
                    justifyContent: "center",
                    alignItems: "center",
                }}
            >
                {/* OffthreadVideo = no delayRender stall; audio is handled separately by <Audio> in index.tsx */}
                <OffthreadVideo
                    src={AVATAR_SRC}
                    muted
                    style={{
                        width: "100%",
                        height: "100%",
                        objectFit: "cover",
                        objectPosition: "center 15%", // Anchor to head, not hands
                        // SOP Part VIII: Interrogation Grade filter
                        filter: "grayscale(0.4) contrast(1.4) brightness(0.6) sepia(0.2)",
                        // Medium close-up + Jump Cut scale
                        transform: `scale(${cameraScale})`,
                        transformOrigin: "center 15%",
                    }}
                />
            </AbsoluteFill>
        </AbsoluteFill>
    );
};
