/**
 * SfxMap — Sound Effect Events
 * ─────────────────────────────
 * GENERATED by pipeline/stages/generate.ts — DO NOT EDIT MANUALLY
 * Topic: "Resulting" (resulting)
 * 18 SFX events mapped to absolute frames
 */

export interface SfxEvent {
    absoluteFrame: number;
    sfxFile: string;
    volume: number;
    startFrom: number;
    label: string;
}

export const SFX_EVENTS: SfxEvent[] = [
    { absoluteFrame: 114, sfxFile: "topics/resulting/sfx/Z_AXIS_SWOOSH.mp3", volume: 0.5, startFrom: 17, label: "S1→S2 Z_AXIS_PORTAL" },
    { absoluteFrame: 189, sfxFile: "topics/resulting/sfx/STOMP_IMPACT.mp3", volume: 0.6, startFrom: 13, label: "S2 STOMP @ HERO_WORD" },
    { absoluteFrame: 204, sfxFile: "topics/resulting/sfx/REDACTION_REVEAL.mp3", volume: 0.4, startFrom: 13, label: "S2 REDACTION_REVEAL @ f90" },
    { absoluteFrame: 400, sfxFile: "topics/resulting/sfx/HIGHLIGHTER_CIRCLE.mp3", volume: 0.35, startFrom: 2, label: "S4 HIGHLIGHTER @ f90" },
    { absoluteFrame: 563, sfxFile: "topics/resulting/sfx/REDACTION_REVEAL.mp3", volume: 0.4, startFrom: 13, label: "S5 REDACTION_REVEAL @ f90" },
    { absoluteFrame: 605, sfxFile: "topics/resulting/sfx/STOMP_IMPACT.mp3", volume: 0.6, startFrom: 13, label: "S5 STOMP @ HERO_WORD" },
    { absoluteFrame: 625, sfxFile: "topics/resulting/sfx/INK_BLEED.mp3", volume: 0.35, startFrom: 4, label: "S5→S6 INK_BLEED" },
    { absoluteFrame: 640, sfxFile: "topics/resulting/sfx/CHART_DRAW.mp3", volume: 0.3, startFrom: 1, label: "S6 CHART_DRAW" },
    { absoluteFrame: 715, sfxFile: "topics/resulting/sfx/HIGHLIGHTER_CIRCLE.mp3", volume: 0.35, startFrom: 2, label: "S6 HIGHLIGHTER @ f90" },
    { absoluteFrame: 764, sfxFile: "topics/resulting/sfx/CHART_DRAW.mp3", volume: 0.3, startFrom: 1, label: "S7 CHART_DRAW" },
    { absoluteFrame: 1017, sfxFile: "topics/resulting/sfx/HIGHLIGHTER_CIRCLE.mp3", volume: 0.35, startFrom: 2, label: "S8 HIGHLIGHTER @ f90" },
    { absoluteFrame: 1066, sfxFile: "topics/resulting/sfx/CHART_DRAW.mp3", volume: 0.3, startFrom: 1, label: "S9 CHART_DRAW" },
    { absoluteFrame: 1141, sfxFile: "topics/resulting/sfx/REDACTION_REVEAL.mp3", volume: 0.4, startFrom: 13, label: "S9 REDACTION_REVEAL @ f90" },
    { absoluteFrame: 1280, sfxFile: "topics/resulting/sfx/STOMP_IMPACT.mp3", volume: 0.6, startFrom: 13, label: "S10 STOMP @ HERO_WORD" },
    { absoluteFrame: 1339, sfxFile: "topics/resulting/sfx/FLASHBULB_SHUTTER.mp3", volume: 0.55, startFrom: 1, label: "S10→S11 FLASHBULB" },
    { absoluteFrame: 1359, sfxFile: "topics/resulting/sfx/STOMP_IMPACT.mp3", volume: 0.6, startFrom: 13, label: "S11 STOMP @ HERO_WORD" },
    { absoluteFrame: 1429, sfxFile: "topics/resulting/sfx/HIGHLIGHTER_CIRCLE.mp3", volume: 0.35, startFrom: 2, label: "S11 HIGHLIGHTER @ f90" },
    { absoluteFrame: 1430, sfxFile: "topics/resulting/sfx/INK_BLEED.mp3", volume: 0.35, startFrom: 4, label: "S11→S12 INK_BLEED" },
];
