/**
 * Topic Data — Runtime Scene Configuration
 * ─────────────────────────────────────────
 * GENERATED by pipeline/stages/generate.ts — DO NOT EDIT MANUALLY
 * Topic: "Resulting" (resulting)
 */

import { C } from "./fonts";

export const TOPIC_META = {
    title: "Resulting",
    slug: "resulting",
    archetype: "HIDDEN_MECHANISM",
} as const;

export const AVATAR_FILE = "topics/resulting/avatar.mp4";
export const NARRATION_FILE = "topics/resulting/narration.mp3";
export const BGM_FILE = "bgm/bgm_dark_high_drone_01.mp3";

export const TOPIC_TRANSITIONS = [
    { from: 1, to: 2, type: "Z_AXIS_PORTAL" },
    { from: 2, to: 3, type: "INFINITE_DESK_LEFT" },
    { from: 3, to: 4, type: "INFINITE_DESK_DOWN" },
    { from: 4, to: 5, type: "INFINITE_DESK_LEFT" },
    { from: 5, to: 6, type: "INK_BLEED" },
    { from: 6, to: 7, type: "INFINITE_DESK_LEFT" },
    { from: 7, to: 8, type: "INFINITE_DESK_RIGHT" },
    { from: 8, to: 9, type: "INFINITE_DESK_DOWN" },
    { from: 9, to: 10, type: "INFINITE_DESK_LEFT" },
    { from: 10, to: 11, type: "FLASHBULB" },
    { from: 11, to: 12, type: "INK_BLEED" }
] as const;

export const TOPIC_SCENES = [
    {
        index: 1,
        heroType: "HERO_VIDEO",
        environment: "VOID",
        layout: "FULL_BLEED",
        physics: "GLIDE",
        narration: "Your best decisions can produce your worst outcomes.",
        heroWord: "outcomes",
        connectiveWord: "BEST",
        videoSrc: "/topics/resulting/assets/scene1_video.mp4",
        imageSrc: "/topics/resulting/assets/scene1_image.jpg",
        declaration: {
            lines: [
            { text: "Best Decisions", size: 88, color: C.CREAM },
            { text: "Worst Outcomes", size: 120, color: C.OXBLOOD }
            ],
            lineStagger: 12,
        },
        microReset: { type: "Z_PUNCH_IN" },
        source: { classification: "EXHIBIT 001 — THE PARADOX", citation: "Outcome Bias, Clearer Thinking 2024" },
    },
    {
        index: 2,
        heroType: "STATEMENT_STATE",
        environment: "VOID",
        layout: "FULL_BLEED",
        physics: "SLAM",
        narration: "That mistake has a name: Resulting.",
        heroWord: "Resulting",
        videoSrc: "/topics/resulting/assets/scene2_video.mp4",
        imageSrc: "/topics/resulting/assets/scene2_image.jpg",
        typography: {
            lines: [
            { text: "RESULTING", type: "HERO", animation: "STOMP", weight: "BLACK", color: C.GOLD }
            ],
            align: "center",
            stagger: 10,
        },
        declaration: {
            lines: [
            { text: "Judge by results.", size: 52, color: C.CREAM_DIM }
            ],
            lineStagger: 10,
        },
        microReset: { type: "REDACTION_REVEAL", label: "THE BIAS" },
        source: { classification: "EXHIBIT 002 — THE NAME", citation: "Baron & Hershey (1988)" },
    },
    {
        index: 3,
        heroType: "STATEMENT_STATE",
        environment: "VOID",
        layout: "FULL_BLEED",
        physics: "SLAM",
        narration: "It quietly destroys fortunes.",
        heroWord: "destroys",
        videoSrc: "/topics/resulting/assets/scene3_video.mp4",
        imageSrc: "/topics/resulting/assets/scene3_image.jpg",
        typography: {
            lines: [
            { text: "DESTROYS", type: "HERO", animation: "REDACTION", weight: "BLACK", color: C.OXBLOOD },
            { text: "FORTUNES", type: "HERO", animation: "SLIDE", weight: "BOLD", color: C.CREAM }
            ],
            align: "flex-start",
            stagger: 8,
        },
        microReset: { type: "Z_PUNCH_IN" },
        source: { classification: "EXHIBIT 003 — THE COST", citation: "Wikipedia: Outcome Bias" },
    },
    {
        index: 4,
        heroType: "EVIDENCE_STATE",
        environment: "VOID",
        layout: "FULL_BLEED",
        physics: "STOP_MOTION",
        narration: "In 2015, one pass play lost the Seattle Seahawks the Super Bowl.",
        heroWord: "lost",
        videoSrc: "/topics/resulting/assets/scene4_video.mp4",
        imageSrc: "/topics/resulting/assets/scene4_image.jpg",
        declaration: {
            lines: [
            { text: "Seahawks Pass", size: 72, color: C.CREAM_DIM },
            { text: "Super Bowl Loss", size: 96, color: C.OXBLOOD }
            ],
            lineStagger: 12,
        },
        evidence: { type: "VERDICT_CARD", leftLabel: "The Call", leftItems: ["Goal Line","Pass Play"], rightLabel: "Outcome", rightItems: ["Intercepted","Patriots Win"] },
        microReset: { type: "HIGHLIGHTER", targetElement: "right-panel" },
        source: { classification: "EXHIBIT 004 — SUPER BOWL", citation: "NFL 2015 Analysis" },
    },
    {
        index: 5,
        heroType: "STATEMENT_STATE",
        environment: "VOID",
        layout: "FULL_BLEED",
        physics: "SLAM",
        narration: "Commentators called it the worst call in history. They were wrong.",
        heroWord: "wrong",
        videoSrc: "/topics/resulting/assets/scene5_video.mp4",
        imageSrc: "/topics/resulting/assets/scene5_image.jpg",
        typography: {
            lines: [
            { text: "WORST CALL", type: "HERO", animation: "STOMP", weight: "BLACK", color: C.CREAM_DIM },
            { text: "They Were", type: "CONNECTIVE", animation: "SLIDE", weight: "REGULAR", color: C.CREAM_FAINT },
            { text: "WRONG.", type: "HERO", animation: "REDACTION", weight: "BLACK", color: C.GOLD }
            ],
            align: "flex-start",
            stagger: 8,
        },
        microReset: { type: "REDACTION_REVEAL", label: "OUTCOME BIAS" },
        source: { classification: "EXHIBIT 005 — MEDIA ERROR", citation: "Clearer Thinking: Outcome Bias" },
    },
    {
        index: 6,
        heroType: "DATA_STATE",
        environment: "VOID",
        layout: "DATA_VICE",
        physics: "SLAM",
        narration: "They judged the decision by the outcome instead of the odds.",
        heroWord: "odds",
        videoSrc: "/topics/resulting/assets/scene6_video.mp4",
        imageSrc: "/topics/resulting/assets/scene6_image.jpg",
        declaration: {
            lines: [
            { text: "By Outcome", size: 72, color: C.CREAM_DIM },
            { text: "Not Odds", size: 96, color: C.OXBLOOD }
            ],
            lineStagger: 10,
        },
        chart: {
            type: "BAR",
            title: "Seahawks Goal Line Odds (%)",
            yUnit: "",
            color: C.GOLD,
            highlightLast: true,
            data: [
            { label: "Run (Marshawn)", value: 70 },
            { label: "Pass (Wilson)", value: 30, sublabel: "Chosen" }
            ],
        },
        microReset: { type: "HIGHLIGHTER", targetElement: "chart-Pass" },
        source: { classification: "EXHIBIT 006 — THE ODDS", citation: "NFL Analytics, 2015" },
    },
    {
        index: 7,
        heroType: "DATA_STATE",
        environment: "SIGNAL_GRID",
        layout: "DATA_VICE",
        physics: "GLIDE",
        narration: "The hidden force is variance. Luck is just noise in the data.",
        heroWord: "variance",
        videoSrc: "/topics/resulting/assets/scene7_video.mp4",
        imageSrc: "/topics/resulting/assets/scene7_image.jpg",
        declaration: {
            lines: [
            { text: "Variance", size: 88, color: C.GOLD },
            { text: "Noise", size: 72, color: C.CREAM_DIM }
            ],
            lineStagger: 12,
        },
        chart: {
            type: "LINE",
            title: "Poker Hands vs Win Rate (%)",
            yUnit: "%",
            color: C.OXBLOOD,
            highlightLast: false,
            data: [
            { label: "100", value: 48 },
            { label: "1K", value: 50 },
            { label: "10K", value: 51 },
            { label: "100K", value: 52 },
            { label: "1M", value: 52.1 }
            ],
            lineLabel: "EV + Noise",
        },
        microReset: { type: "Z_PUNCH_IN" },
        source: { classification: "EXHIBIT 007 — VARIANCE", citation: "Poker Variance Studies, 2024" },
    },
    {
        index: 8,
        heroType: "EVIDENCE_STATE",
        environment: "VOID",
        layout: "FULL_BLEED",
        physics: "STOP_MOTION",
        narration: "If you drive home drunk and survive, was it a good decision?",
        heroWord: "good",
        videoSrc: "/topics/resulting/assets/scene8_video.mp4",
        imageSrc: "/topics/resulting/assets/scene8_image.jpg",
        declaration: {
            lines: [
            { text: "Drunk Drive", size: 80, color: C.CREAM },
            { text: "Survived?", size: 100, color: C.OXBLOOD }
            ],
            lineStagger: 12,
        },
        evidence: { type: "VERDICT_CARD", leftLabel: "Process", leftItems: ["Terrible Odds","High Risk"], rightLabel: "Outcome", rightItems: ["Survived","Good Call?"] },
        microReset: { type: "HIGHLIGHTER", targetElement: "right-panel" },
        source: { classification: "EXHIBIT 008 — SURVIVOR BIAS", citation: "Outcome Bias Examples" },
    },
    {
        index: 9,
        heroType: "DATA_STATE",
        environment: "VOID",
        layout: "OFFSET_STACK",
        physics: "SLAM",
        narration: "Markets reward the lucky amateur and punish the disciplined professional.",
        heroWord: "reward",
        videoSrc: "/topics/resulting/assets/scene9_video.mp4",
        imageSrc: "/topics/resulting/assets/scene9_image.jpg",
        declaration: {
            lines: [
            { text: "Lucky Amateur", size: 72, color: C.GOLD },
            { text: "Pro Punished", size: 88, color: C.OXBLOOD }
            ],
            lineStagger: 10,
        },
        chart: {
            type: "BAR",
            title: "Hedge Fund Returns (1Y, %)",
            yUnit: "",
            color: C.GOLD,
            highlightLast: true,
            data: [
            { label: "Avg Pro", value: 8 },
            { label: "Discipline", value: 12 },
            { label: "Lucky Fund", value: 45 }
            ],
        },
        microReset: { type: "REDACTION_REVEAL", label: "LUCK WINS" },
        source: { classification: "EXHIBIT 009 — MARKET NOISE", citation: "HFR Index, 2024" },
    },
    {
        index: 10,
        heroType: "STATEMENT_STATE",
        environment: "VOID",
        layout: "FULL_BLEED",
        physics: "SLAM",
        narration: "Over time, that incentive structure erodes real capital.",
        heroWord: "erodes",
        videoSrc: "/topics/resulting/assets/scene10_video.mp4",
        imageSrc: "/topics/resulting/assets/scene10_image.jpg",
        typography: {
            lines: [
            { text: "ERODES", type: "HERO", animation: "STOMP", weight: "BLACK", color: C.OXBLOOD },
            { text: "REAL CAPITAL", type: "HERO", animation: "SLIDE", weight: "BOLD", color: C.CREAM }
            ],
            align: "center",
            stagger: 8,
        },
        dataTicker: {
            from: 100,
            to: 45,
            prefix: "",
            suffix: "%",
            decimals: 0,
            label: "Capital after 10Y Resulting",
            color: C.OXBLOOD,
        },
        microReset: { type: "Z_PUNCH_IN" },
        source: { classification: "EXHIBIT 010 — CAPITAL LOSS", citation: "McKinsey: Decision Biases" },
    },
    {
        index: 11,
        heroType: "STATEMENT_STATE",
        environment: "VOID",
        layout: "FULL_BLEED",
        physics: "GLIDE",
        narration: "Winners separate process from outcome.",
        heroWord: "separate",
        videoSrc: "/topics/resulting/assets/scene11_video.mp4",
        imageSrc: "/topics/resulting/assets/scene11_image.jpg",
        typography: {
            lines: [
            { text: "PROCESS", type: "HERO", animation: "SLIDE", weight: "BLACK", color: C.GOLD },
            { text: "vs", type: "CONNECTIVE", animation: "SLIDE", weight: "LIGHT", color: C.CREAM_FAINT },
            { text: "OUTCOME", type: "HERO", animation: "STOMP", weight: "BLACK", color: C.CREAM }
            ],
            align: "center",
            stagger: 10,
        },
        microReset: { type: "HIGHLIGHTER", targetElement: "PROCESS" },
        source: { classification: "EXHIBIT 011 — WINNER'S EDGE", citation: "Thinking in Bets, Duke 2018" },
    },
    {
        index: 12,
        heroType: "HERO_VIDEO",
        environment: "IMMERSIVE_BLEED",
        layout: "FULL_BLEED",
        physics: "GLIDE",
        narration: "You evaluate the bet before the card is revealed. Stop judging results. Start thinking in bets.",
        heroWord: "bets",
        videoSrc: "/topics/resulting/assets/scene12_video.mp4",
        imageSrc: "/topics/resulting/assets/scene12_image.jpg",
        declaration: {
            lines: [
            { text: "Think in Bets", size: 96, color: C.GOLD },
            { text: "Before Results", size: 72, color: C.CREAM }
            ],
            lineStagger: 14,
        },
        microReset: { type: "Z_PUNCH_IN" },
        source: { classification: "CLASSIFIED — FINAL VERDICT", citation: "Project Variance Shield" },
    }
] as const;
